<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Deskripsi_btn-close btn-close-white _f67776 (1)</name>
   <tag></tag>
   <elementGuidId>c56ed335-5ef5-465b-b7be-78914644b6da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-close.btn-close-white.position-absolute.top-0.start-100.translate-middle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5bedda5f-4b77-41c3-a2fd-427f003f96fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98a5e665-f5b8-42a7-973b-5ddf14cf65ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.parentElement.remove()</value>
      <webElementGuid>ef7a98a4-8044-4069-8c8e-89c7fcfa5301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close btn-close-white position-absolute top-0 start-100 translate-middle</value>
      <webElementGuid>91bfde70-ce0a-40fc-ba2d-4f98a270cd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>18e9e13b-a627-46cc-9ede-25fc1296a709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-images&quot;)/div[@class=&quot;form-image-preview position-relative rounded-4 overflow-hidden&quot;]/button[@class=&quot;btn-close btn-close-white position-absolute top-0 start-100 translate-middle&quot;]</value>
      <webElementGuid>9a18e212-24b9-4d2c-9d22-4f6c0d2a3162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>e30c5473-b0bf-4ca7-9820-4c4fbee4c1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-images']/div/button</value>
      <webElementGuid>e34737cf-285c-4d48-b6ba-fe3ccede8701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>3d13ec93-3a13-4648-928c-e5edc0722a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>74f16ebd-a848-45e9-a97e-c5cb11979a46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
