<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Deskripsi_productimages (1)</name>
   <tag></tag>
   <elementGuidId>271c8643-0b95-4b6c-a773-d58130d85e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_images</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_images']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84668d80-8d89-4dee-a1ed-844a59c54620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>4c11c132-8943-4d16-a506-af058e305041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none</value>
      <webElementGuid>1a0752ec-1c58-498e-82ec-e3243d1128ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/png, image/jpeg</value>
      <webElementGuid>aa85e4e1-b670-46a7-a98a-8d8a3fe8fcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-direct-upload-url</name>
      <type>Main</type>
      <value>https://secondhand.binaracademy.org/rails/active_storage/direct_uploads</value>
      <webElementGuid>ea690cf1-b44b-44d6-9df0-808cdb7961c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>3fb054b1-57a3-4e47-864a-420d06ba6667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[images][]</value>
      <webElementGuid>1e43f322-2aaa-4593-a95e-8f1b9915a945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_images</value>
      <webElementGuid>32d3677e-4ae5-47e7-b655-053dd653bc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_images&quot;)</value>
      <webElementGuid>39bf874a-a6ed-41b8-bd30-a3f74feb6099</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_images']</value>
      <webElementGuid>06022411-d389-4a14-8748-0d72109567ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-images']/input[2]</value>
      <webElementGuid>db623945-bf23-409b-b1fb-863af2ba0546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>a655b370-b3ee-4827-9b0c-242525fa5f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'product[images][]' and @id = 'product_images']</value>
      <webElementGuid>da8d8c6e-7bb2-4b0b-b504-bf4d97b91993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
