<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Deskripsi_productimages</name>
   <tag></tag>
   <elementGuidId>f140cd4a-4492-4fe8-90ca-cf6e7377f55e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_images</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_images']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbe08f2c-4875-4708-a127-37ed4d102fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>bd715d11-03a2-4579-b27d-7515df386ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none</value>
      <webElementGuid>ffa01fc4-766b-4b0a-a4c6-dbd331c53c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/png, image/jpeg</value>
      <webElementGuid>681a337c-c169-4862-a0c4-09bb9882b65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-direct-upload-url</name>
      <type>Main</type>
      <value>https://secondhand.binaracademy.org/rails/active_storage/direct_uploads</value>
      <webElementGuid>d4d03c6c-d33e-40a7-a516-3cd42e7d640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>53d78fec-d85f-42ef-9803-1e150ae67e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[images][]</value>
      <webElementGuid>788ba377-fd4f-46b7-84b0-cb132ee764d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_images</value>
      <webElementGuid>c3dc2b53-4c45-48d2-9df0-a72905315e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_images&quot;)</value>
      <webElementGuid>7990fd22-452e-4b18-b3a4-a340ecba2411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_images']</value>
      <webElementGuid>88159750-c8cf-4601-88dc-1eb2473b97c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-images']/input[2]</value>
      <webElementGuid>b8ed1a18-ce71-4585-a52c-d7277acca06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>f064f540-0ef3-4795-9c52-9ac7c047b782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'product[images][]' and @id = 'product_images']</value>
      <webElementGuid>70a60518-c79c-405c-80c5-c68643e01d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
