<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Handphone_userphone_number</name>
   <tag></tag>
   <elementGuidId>c476f2d4-d533-4cc3-b5d6-544939fb049a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_phone_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_phone_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f354d0be-8ac1-44a9-bc62-41e6da681ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-4 p-3</value>
      <webElementGuid>abd8fb07-3cc7-4933-b21f-b6b7cff82cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>contoh: +628123456789</value>
      <webElementGuid>4aefd43b-821a-4e56-a9e3-515d50a98960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d3345f27-2324-4f65-bbdd-426d65008c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17796c02-555b-4df4-ba18-8786b72e931d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[phone_number]</value>
      <webElementGuid>97eb561a-8e6e-4c7a-a60c-6d5e6bd39152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_phone_number</value>
      <webElementGuid>3ee41d17-a6b1-4859-b0d9-c4fd81aecaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_phone_number&quot;)</value>
      <webElementGuid>b348ca33-f69b-45c2-9da1-7bf002798626</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_phone_number']</value>
      <webElementGuid>7b7701c9-6d6c-4beb-919e-77401b7dfcc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>b8f52653-afa9-4ca2-bdfe-8dee3b177236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'contoh: +628123456789' and @type = 'text' and @name = 'user[phone_number]' and @id = 'user_phone_number']</value>
      <webElementGuid>f081576e-cd50-4d12-8546-e2bc947a6057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
