<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lengkapi Info Akun_useravatar</name>
   <tag></tag>
   <elementGuidId>7648c7ee-7e4c-408f-9fe9-d8e62a3774f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-avatar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-avatar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>354880ec-395e-4d6a-8af5-71769ad6b118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-4 p-3 d-none</value>
      <webElementGuid>418f4ff1-6cef-4582-a8ec-dca5299fe268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-avatar</value>
      <webElementGuid>011bf481-45b1-42bf-8269-c257097e8805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/png, image/jpeg</value>
      <webElementGuid>9425ae4e-f537-485d-a23d-dfe4c7cbcda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-direct-upload-url</name>
      <type>Main</type>
      <value>https://secondhand.binaracademy.org/rails/active_storage/direct_uploads</value>
      <webElementGuid>a7d5a62c-58d7-4ece-a356-0041528886bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ad1b875a-688c-4fa4-a076-31f2427cef15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[avatar]</value>
      <webElementGuid>00074adc-6b16-477f-8a06-ed807c6a09a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-avatar&quot;)</value>
      <webElementGuid>b35cbf6c-0edf-46ef-b468-48ed35ae6def</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-avatar']</value>
      <webElementGuid>45ce8bf1-2a4f-4b2d-a169-8d044c4676d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-avatar-view']/input</value>
      <webElementGuid>86a4c82f-8817-4fa0-a3d8-45b5949f6c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>38d4c9e5-abc5-4ac5-893b-f16e1082e4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form-avatar' and @type = 'file' and @name = 'user[avatar]']</value>
      <webElementGuid>13b65b6e-0b46-4e59-bb8c-46274504de97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
